version: "3.8"
services:
    web:
        container_name: web
        image: node
        working_dir: /app
        volumes:
            - ../:/app
        links:
            - mongodb
            - redisdb
        command: /app/.entrypoint.sh
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        volumes:
            - ../db/mongo:/data/db
    redisdb:
        container_name: redisdb
        image: redis
        volumes:
            - ../db/redis:/data
