version: "3.8"
services:
    web:
        container_name: web
        build:
            context: ../
        working_dir: /app
        volumes:
            - ../:/app
            - /app/node_modules
        links:
            - mongodb
            - redisdb
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        volumes:
            - ../db/mongo:/data/db
    redisdb:
        container_name: redisdb
        image: redis
        volumes:
            - ../db/redis:/data
