version: "3.6"
services:
    web:
        container_name: web
        build:
            context: ../
        working_dir: /src
        volumes:
            - ../:/src
        links:
            - db
    db:
        container_name: db
        image: mongo
        restart: always
        volumes:
            - ../db:/data/db
