version: "3.8"
services:
    web:
        build:
            context: ../
            target: production
        command: yarn start
        env_file: ../.env.production
        volumes:
            - ../:/src
            - /src/node_modules
            - /src/dist
